version: "3.8"

services:
  # --- BACKEND SERVICE ---
  backend:
    build: 
      context: ./backend
      target: production
    ports: 
      - "4000:4000"
    environment:
      - DATABASE_URL=file:/app/data/dev.db
      - NODE_ENV=production
    volumes:
      - ai_studio_db:/app/data
    command: npm run start
    restart: always

  # --- FRONTEND SERVICE ---
  frontend:
    build: 
      context: ./frontend
      target: production
    ports: 
      - "3000:5173" 
    environment:
      - VITE_API_BASE_URL=http://backend:4000/api
      - NODE_ENV=production
    depends_on:
      - backend
    restart: always

# Define the persistent volume
volumes:
  ai_studio_db:
    driver: local