name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Install backend deps
        run: |
          cd backend
          npm ci
      
      - name: Setup Test Database
        run: echo "DATABASE_URL=file:./test.db" > backend/.env.test
        
      - name: Generate Prisma Client
        run: npx prisma generate --schema backend/prisma/schema.prisma
        
      - name: Run backend tests
        run: |
          cd backend
          npm test -- --coverage
          
      - name: Upload backend coverage
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: backend/coverage

  frontend:
    runs-on: ubuntu-latest
    needs: [backend] 
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Install frontend deps
        run: |
          cd frontend
          npm ci
          
      - name: Run frontend tests
        run: |
          cd frontend
          npm run coverage -- --watchAll=false
          
      - name: Upload frontend coverage
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage
          path: frontend/coverage